name: Generate IPFS .car file

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
    - name: Write commit hash to index file
      run: sed -i s/COMMIT_HASH/$(git rev-parse HEAD)/ index.html
    - name: Build .car file
      run: |
        npm install -g ipfs-car && \
        ipfs-car --wrapWithDirectory false --pack . --output output.car
    - uses: actions/upload-artifact@v2
      with:
        path: output.car
